[build]
target = "mos-unknown-none"

[target.mos-unknown-none]
rustflags = [
    "-C", "target-cpu=mos65c02",
    "-C", "link-arg=-Tlink.ld",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-nostdlib",
]

[unstable]
build-std = ["core"]