# the commented out pieces are so my IDE can understand the code without me needing to compile rust-mos on my system :^)

[build]
#target = "mos-unknown-none"

[target.mos-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlink.ld",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-nostdlib",
]

[unstable]
#build-std = ["core"]